// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/xilidan/backend/services/sso/storage/postgres/ent/organizationusers"
)

// OrganizationUsers is the model entity for the OrganizationUsers schema.
type OrganizationUsers struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrganizationUsersQuery when eager-loading is set.
	Edges              OrganizationUsersEdges `json:"edges"`
	organization_users *uuid.UUID
	user_organizations *uuid.UUID
	selectValues       sql.SelectValues
}

// OrganizationUsersEdges holds the relations/edges for other nodes in the graph.
type OrganizationUsersEdges struct {
	// User holds the value of the user edge.
	User []*User `json:"user,omitempty"`
	// Organization holds the value of the organization edge.
	Organization []*Organization `json:"organization,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationUsersEdges) UserOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OrganizationOrErr returns the Organization value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationUsersEdges) OrganizationOrErr() ([]*Organization, error) {
	if e.loadedTypes[1] {
		return e.Organization, nil
	}
	return nil, &NotLoadedError{edge: "organization"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrganizationUsers) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case organizationusers.FieldCreatedAt, organizationusers.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case organizationusers.FieldID:
			values[i] = new(uuid.UUID)
		case organizationusers.ForeignKeys[0]: // organization_users
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case organizationusers.ForeignKeys[1]: // user_organizations
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrganizationUsers fields.
func (_m *OrganizationUsers) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case organizationusers.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case organizationusers.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case organizationusers.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case organizationusers.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field organization_users", values[i])
			} else if value.Valid {
				_m.organization_users = new(uuid.UUID)
				*_m.organization_users = *value.S.(*uuid.UUID)
			}
		case organizationusers.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_organizations", values[i])
			} else if value.Valid {
				_m.user_organizations = new(uuid.UUID)
				*_m.user_organizations = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrganizationUsers.
// This includes values selected through modifiers, order, etc.
func (_m *OrganizationUsers) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the OrganizationUsers entity.
func (_m *OrganizationUsers) QueryUser() *UserQuery {
	return NewOrganizationUsersClient(_m.config).QueryUser(_m)
}

// QueryOrganization queries the "organization" edge of the OrganizationUsers entity.
func (_m *OrganizationUsers) QueryOrganization() *OrganizationQuery {
	return NewOrganizationUsersClient(_m.config).QueryOrganization(_m)
}

// Update returns a builder for updating this OrganizationUsers.
// Note that you need to call OrganizationUsers.Unwrap() before calling this method if this OrganizationUsers
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrganizationUsers) Update() *OrganizationUsersUpdateOne {
	return NewOrganizationUsersClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrganizationUsers entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrganizationUsers) Unwrap() *OrganizationUsers {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrganizationUsers is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrganizationUsers) String() string {
	var builder strings.Builder
	builder.WriteString("OrganizationUsers(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OrganizationUsersSlice is a parsable slice of OrganizationUsers.
type OrganizationUsersSlice []*OrganizationUsers
