// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/xilidan/backend/services/sso/storage/postgres/ent/organizationusers"
	"github.com/xilidan/backend/services/sso/storage/postgres/ent/predicate"
)

// OrganizationUsersDelete is the builder for deleting a OrganizationUsers entity.
type OrganizationUsersDelete struct {
	config
	hooks    []Hook
	mutation *OrganizationUsersMutation
}

// Where appends a list predicates to the OrganizationUsersDelete builder.
func (_d *OrganizationUsersDelete) Where(ps ...predicate.OrganizationUsers) *OrganizationUsersDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OrganizationUsersDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrganizationUsersDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OrganizationUsersDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(organizationusers.Table, sqlgraph.NewFieldSpec(organizationusers.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OrganizationUsersDeleteOne is the builder for deleting a single OrganizationUsers entity.
type OrganizationUsersDeleteOne struct {
	_d *OrganizationUsersDelete
}

// Where appends a list predicates to the OrganizationUsersDelete builder.
func (_d *OrganizationUsersDeleteOne) Where(ps ...predicate.OrganizationUsers) *OrganizationUsersDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OrganizationUsersDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{organizationusers.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrganizationUsersDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
