// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: sso/sso.proto

package sso

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckReq) Reset() {
	*x = HealthCheckReq{}
	mi := &file_sso_sso_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckReq) ProtoMessage() {}

func (x *HealthCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckReq.ProtoReflect.Descriptor instead.
func (*HealthCheckReq) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResp) Reset() {
	*x = HealthCheckResp{}
	mi := &file_sso_sso_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResp) ProtoMessage() {}

func (x *HealthCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResp.ProtoReflect.Descriptor instead.
func (*HealthCheckResp) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surname       *string                `protobuf:"bytes,3,opt,name=surname,proto3,oneof" json:"surname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PositionId    int64                  `protobuf:"varint,5,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	Job           string                 `protobuf:"bytes,6,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_sso_sso_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetSurname() string {
	if x != nil && x.Surname != nil {
		return *x.Surname
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

func (x *User) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsReviewer    bool                   `protobuf:"varint,3,opt,name=is_reviewer,json=isReviewer,proto3" json:"is_reviewer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_sso_sso_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{3}
}

func (x *Position) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Position) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Position) GetIsReviewer() bool {
	if x != nil {
		return x.IsReviewer
	}
	return false
}

type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Positions     []*Position            `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions,omitempty"`
	Users         []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_sso_sso_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{4}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *Organization) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type RegisterReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname         *string                `protobuf:"bytes,2,opt,name=surname,proto3,oneof" json:"surname,omitempty"`
	Email           string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	PasswordConfirm string                 `protobuf:"bytes,5,opt,name=password_confirm,json=passwordConfirm,proto3" json:"password_confirm,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_sso_sso_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterReq) GetSurname() string {
	if x != nil && x.Surname != nil {
		return *x.Surname
	}
	return ""
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetPasswordConfirm() string {
	if x != nil {
		return x.PasswordConfirm
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_sso_sso_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_sso_sso_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{7}
}

func (x *LoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_sso_sso_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_sso_sso_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResp) Reset() {
	*x = GetUserResp{}
	mi := &file_sso_sso_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResp) ProtoMessage() {}

func (x *GetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResp.ProtoReflect.Descriptor instead.
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateOrganizationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Positions     []*Position            `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	Users         []*User                `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationReq) Reset() {
	*x = CreateOrganizationReq{}
	mi := &file_sso_sso_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationReq) ProtoMessage() {}

func (x *CreateOrganizationReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationReq.ProtoReflect.Descriptor instead.
func (*CreateOrganizationReq) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{11}
}

func (x *CreateOrganizationReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationReq) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *CreateOrganizationReq) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type CreateOrganizationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationResp) Reset() {
	*x = CreateOrganizationResp{}
	mi := &file_sso_sso_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationResp) ProtoMessage() {}

func (x *CreateOrganizationResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationResp.ProtoReflect.Descriptor instead.
func (*CreateOrganizationResp) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{12}
}

func (x *CreateOrganizationResp) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type GetOrganizationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationReq) Reset() {
	*x = GetOrganizationReq{}
	mi := &file_sso_sso_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationReq) ProtoMessage() {}

func (x *GetOrganizationReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationReq.ProtoReflect.Descriptor instead.
func (*GetOrganizationReq) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrganizationReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrganizationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrganizationResp) Reset() {
	*x = GetOrganizationResp{}
	mi := &file_sso_sso_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrganizationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrganizationResp) ProtoMessage() {}

func (x *GetOrganizationResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrganizationResp.ProtoReflect.Descriptor instead.
func (*GetOrganizationResp) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{14}
}

func (x *GetOrganizationResp) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

type GetPositionsReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetPositionsReq) Reset() {
	*x = GetPositionsReq{}
	mi := &file_sso_sso_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsReq) ProtoMessage() {}

func (x *GetPositionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsReq.ProtoReflect.Descriptor instead.
func (*GetPositionsReq) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{15}
}

func (x *GetPositionsReq) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type GetPositionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionsResp) Reset() {
	*x = GetPositionsResp{}
	mi := &file_sso_sso_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsResp) ProtoMessage() {}

func (x *GetPositionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsResp.ProtoReflect.Descriptor instead.
func (*GetPositionsResp) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{16}
}

func (x *GetPositionsResp) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type UpdateOrganizationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Positions     []*Position            `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions,omitempty"`
	Users         []*User                `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationReq) Reset() {
	*x = UpdateOrganizationReq{}
	mi := &file_sso_sso_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationReq) ProtoMessage() {}

func (x *UpdateOrganizationReq) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationReq.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationReq) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateOrganizationReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateOrganizationReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOrganizationReq) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *UpdateOrganizationReq) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type UpdateOrganizationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Organization  *Organization          `protobuf:"bytes,1,opt,name=organization,proto3" json:"organization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationResp) Reset() {
	*x = UpdateOrganizationResp{}
	mi := &file_sso_sso_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationResp) ProtoMessage() {}

func (x *UpdateOrganizationResp) ProtoReflect() protoreflect.Message {
	mi := &file_sso_sso_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationResp.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationResp) Descriptor() ([]byte, []int) {
	return file_sso_sso_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateOrganizationResp) GetOrganization() *Organization {
	if x != nil {
		return x.Organization
	}
	return nil
}

var File_sso_sso_proto protoreflect.FileDescriptor

const file_sso_sso_proto_rawDesc = "" +
	"\n" +
	"\rsso/sso.proto\x12\x03sso\"\x10\n" +
	"\x0eHealthCheckReq\")\n" +
	"\x0fHealthCheckResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\x9e\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\asurname\x18\x03 \x01(\tH\x00R\asurname\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1f\n" +
	"\vposition_id\x18\x05 \x01(\x03R\n" +
	"positionId\x12\x10\n" +
	"\x03job\x18\x06 \x01(\tR\x03jobB\n" +
	"\n" +
	"\b_surname\"O\n" +
	"\bPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vis_reviewer\x18\x03 \x01(\bR\n" +
	"isReviewer\"\x80\x01\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\tpositions\x18\x03 \x03(\v2\r.sso.PositionR\tpositions\x12\x1f\n" +
	"\x05users\x18\x04 \x03(\v2\t.sso.UserR\x05users\"\xa9\x01\n" +
	"\vRegisterReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\asurname\x18\x02 \x01(\tH\x00R\asurname\x88\x01\x01\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12)\n" +
	"\x10password_confirm\x18\x05 \x01(\tR\x0fpasswordConfirmB\n" +
	"\n" +
	"\b_surname\"$\n" +
	"\fRegisterResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"<\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"!\n" +
	"\tLoginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"%\n" +
	"\n" +
	"GetUserReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\",\n" +
	"\vGetUserResp\x12\x1d\n" +
	"\x04user\x18\x01 \x01(\v2\t.sso.UserR\x04user\"y\n" +
	"\x15CreateOrganizationReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12+\n" +
	"\tpositions\x18\x02 \x03(\v2\r.sso.PositionR\tpositions\x12\x1f\n" +
	"\x05users\x18\x03 \x03(\v2\t.sso.UserR\x05users\"O\n" +
	"\x16CreateOrganizationResp\x125\n" +
	"\forganization\x18\x01 \x01(\v2\x11.sso.OrganizationR\forganization\"$\n" +
	"\x12GetOrganizationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x13GetOrganizationResp\x125\n" +
	"\forganization\x18\x01 \x01(\v2\x11.sso.OrganizationR\forganization\":\n" +
	"\x0fGetPositionsReq\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"?\n" +
	"\x10GetPositionsResp\x12+\n" +
	"\tpositions\x18\x02 \x03(\v2\r.sso.PositionR\tpositions\"\x89\x01\n" +
	"\x15UpdateOrganizationReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\tpositions\x18\x03 \x03(\v2\r.sso.PositionR\tpositions\x12\x1f\n" +
	"\x05users\x18\x04 \x03(\v2\t.sso.UserR\x05users\"O\n" +
	"\x16UpdateOrganizationResp\x125\n" +
	"\forganization\x18\x01 \x01(\v2\x11.sso.OrganizationR\forganization2\xee\x03\n" +
	"\n" +
	"SsoService\x128\n" +
	"\vHealthCheck\x12\x13.sso.HealthCheckReq\x1a\x14.sso.HealthCheckResp\x12/\n" +
	"\bRegister\x12\x10.sso.RegisterReq\x1a\x11.sso.RegisterResp\x12&\n" +
	"\x05Login\x12\r.sso.LoginReq\x1a\x0e.sso.LoginResp\x12,\n" +
	"\aGetUser\x12\x0f.sso.GetUserReq\x1a\x10.sso.GetUserResp\x12M\n" +
	"\x12CreateOrganization\x12\x1a.sso.CreateOrganizationReq\x1a\x1b.sso.CreateOrganizationResp\x12D\n" +
	"\x0fGetOrganization\x12\x17.sso.GetOrganizationReq\x1a\x18.sso.GetOrganizationResp\x12;\n" +
	"\fGetPositions\x12\x14.sso.GetPositionsReq\x1a\x15.sso.GetPositionsResp\x12M\n" +
	"\x12UpdateOrganization\x12\x1a.sso.UpdateOrganizationReq\x1a\x1b.sso.UpdateOrganizationRespB\x11Z\x0fspecs/proto/ssob\x06proto3"

var (
	file_sso_sso_proto_rawDescOnce sync.Once
	file_sso_sso_proto_rawDescData []byte
)

func file_sso_sso_proto_rawDescGZIP() []byte {
	file_sso_sso_proto_rawDescOnce.Do(func() {
		file_sso_sso_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sso_sso_proto_rawDesc), len(file_sso_sso_proto_rawDesc)))
	})
	return file_sso_sso_proto_rawDescData
}

var file_sso_sso_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_sso_sso_proto_goTypes = []any{
	(*HealthCheckReq)(nil),         // 0: sso.HealthCheckReq
	(*HealthCheckResp)(nil),        // 1: sso.HealthCheckResp
	(*User)(nil),                   // 2: sso.User
	(*Position)(nil),               // 3: sso.Position
	(*Organization)(nil),           // 4: sso.Organization
	(*RegisterReq)(nil),            // 5: sso.RegisterReq
	(*RegisterResp)(nil),           // 6: sso.RegisterResp
	(*LoginReq)(nil),               // 7: sso.LoginReq
	(*LoginResp)(nil),              // 8: sso.LoginResp
	(*GetUserReq)(nil),             // 9: sso.GetUserReq
	(*GetUserResp)(nil),            // 10: sso.GetUserResp
	(*CreateOrganizationReq)(nil),  // 11: sso.CreateOrganizationReq
	(*CreateOrganizationResp)(nil), // 12: sso.CreateOrganizationResp
	(*GetOrganizationReq)(nil),     // 13: sso.GetOrganizationReq
	(*GetOrganizationResp)(nil),    // 14: sso.GetOrganizationResp
	(*GetPositionsReq)(nil),        // 15: sso.GetPositionsReq
	(*GetPositionsResp)(nil),       // 16: sso.GetPositionsResp
	(*UpdateOrganizationReq)(nil),  // 17: sso.UpdateOrganizationReq
	(*UpdateOrganizationResp)(nil), // 18: sso.UpdateOrganizationResp
}
var file_sso_sso_proto_depIdxs = []int32{
	3,  // 0: sso.Organization.positions:type_name -> sso.Position
	2,  // 1: sso.Organization.users:type_name -> sso.User
	2,  // 2: sso.GetUserResp.user:type_name -> sso.User
	3,  // 3: sso.CreateOrganizationReq.positions:type_name -> sso.Position
	2,  // 4: sso.CreateOrganizationReq.users:type_name -> sso.User
	4,  // 5: sso.CreateOrganizationResp.organization:type_name -> sso.Organization
	4,  // 6: sso.GetOrganizationResp.organization:type_name -> sso.Organization
	3,  // 7: sso.GetPositionsResp.positions:type_name -> sso.Position
	3,  // 8: sso.UpdateOrganizationReq.positions:type_name -> sso.Position
	2,  // 9: sso.UpdateOrganizationReq.users:type_name -> sso.User
	4,  // 10: sso.UpdateOrganizationResp.organization:type_name -> sso.Organization
	0,  // 11: sso.SsoService.HealthCheck:input_type -> sso.HealthCheckReq
	5,  // 12: sso.SsoService.Register:input_type -> sso.RegisterReq
	7,  // 13: sso.SsoService.Login:input_type -> sso.LoginReq
	9,  // 14: sso.SsoService.GetUser:input_type -> sso.GetUserReq
	11, // 15: sso.SsoService.CreateOrganization:input_type -> sso.CreateOrganizationReq
	13, // 16: sso.SsoService.GetOrganization:input_type -> sso.GetOrganizationReq
	15, // 17: sso.SsoService.GetPositions:input_type -> sso.GetPositionsReq
	17, // 18: sso.SsoService.UpdateOrganization:input_type -> sso.UpdateOrganizationReq
	1,  // 19: sso.SsoService.HealthCheck:output_type -> sso.HealthCheckResp
	6,  // 20: sso.SsoService.Register:output_type -> sso.RegisterResp
	8,  // 21: sso.SsoService.Login:output_type -> sso.LoginResp
	10, // 22: sso.SsoService.GetUser:output_type -> sso.GetUserResp
	12, // 23: sso.SsoService.CreateOrganization:output_type -> sso.CreateOrganizationResp
	14, // 24: sso.SsoService.GetOrganization:output_type -> sso.GetOrganizationResp
	16, // 25: sso.SsoService.GetPositions:output_type -> sso.GetPositionsResp
	18, // 26: sso.SsoService.UpdateOrganization:output_type -> sso.UpdateOrganizationResp
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_sso_sso_proto_init() }
func file_sso_sso_proto_init() {
	if File_sso_sso_proto != nil {
		return
	}
	file_sso_sso_proto_msgTypes[2].OneofWrappers = []any{}
	file_sso_sso_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sso_sso_proto_rawDesc), len(file_sso_sso_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sso_sso_proto_goTypes,
		DependencyIndexes: file_sso_sso_proto_depIdxs,
		MessageInfos:      file_sso_sso_proto_msgTypes,
	}.Build()
	File_sso_sso_proto = out.File
	file_sso_sso_proto_goTypes = nil
	file_sso_sso_proto_depIdxs = nil
}
