// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: specs/proto/asr/asr.proto

package asr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckReq) Reset() {
	*x = HealthCheckReq{}
	mi := &file_specs_proto_asr_asr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckReq) ProtoMessage() {}

func (x *HealthCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_asr_asr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckReq.ProtoReflect.Descriptor instead.
func (*HealthCheckReq) Descriptor() ([]byte, []int) {
	return file_specs_proto_asr_asr_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResp) Reset() {
	*x = HealthCheckResp{}
	mi := &file_specs_proto_asr_asr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResp) ProtoMessage() {}

func (x *HealthCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_asr_asr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResp.ProtoReflect.Descriptor instead.
func (*HealthCheckResp) Descriptor() ([]byte, []int) {
	return file_specs_proto_asr_asr_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResp) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type TranscribeAudioReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	MeetingId     string                 `protobuf:"bytes,2,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"` // wav, mp3, etc.
	SampleRate    int32                  `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeAudioReq) Reset() {
	*x = TranscribeAudioReq{}
	mi := &file_specs_proto_asr_asr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeAudioReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeAudioReq) ProtoMessage() {}

func (x *TranscribeAudioReq) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_asr_asr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeAudioReq.ProtoReflect.Descriptor instead.
func (*TranscribeAudioReq) Descriptor() ([]byte, []int) {
	return file_specs_proto_asr_asr_proto_rawDescGZIP(), []int{2}
}

func (x *TranscribeAudioReq) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *TranscribeAudioReq) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *TranscribeAudioReq) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *TranscribeAudioReq) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type TranscribeAudioResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	MeetingId     string                 `protobuf:"bytes,2,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeAudioResp) Reset() {
	*x = TranscribeAudioResp{}
	mi := &file_specs_proto_asr_asr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeAudioResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeAudioResp) ProtoMessage() {}

func (x *TranscribeAudioResp) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_asr_asr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeAudioResp.ProtoReflect.Descriptor instead.
func (*TranscribeAudioResp) Descriptor() ([]byte, []int) {
	return file_specs_proto_asr_asr_proto_rawDescGZIP(), []int{3}
}

func (x *TranscribeAudioResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscribeAudioResp) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *TranscribeAudioResp) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type GetTranscriptionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscriptionReq) Reset() {
	*x = GetTranscriptionReq{}
	mi := &file_specs_proto_asr_asr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscriptionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscriptionReq) ProtoMessage() {}

func (x *GetTranscriptionReq) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_asr_asr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscriptionReq.ProtoReflect.Descriptor instead.
func (*GetTranscriptionReq) Descriptor() ([]byte, []int) {
	return file_specs_proto_asr_asr_proto_rawDescGZIP(), []int{4}
}

func (x *GetTranscriptionReq) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

type GetTranscriptionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	FullText      string                 `protobuf:"bytes,2,opt,name=full_text,json=fullText,proto3" json:"full_text,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTranscriptionResp) Reset() {
	*x = GetTranscriptionResp{}
	mi := &file_specs_proto_asr_asr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTranscriptionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTranscriptionResp) ProtoMessage() {}

func (x *GetTranscriptionResp) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_asr_asr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTranscriptionResp.ProtoReflect.Descriptor instead.
func (*GetTranscriptionResp) Descriptor() ([]byte, []int) {
	return file_specs_proto_asr_asr_proto_rawDescGZIP(), []int{5}
}

func (x *GetTranscriptionResp) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *GetTranscriptionResp) GetFullText() string {
	if x != nil {
		return x.FullText
	}
	return ""
}

func (x *GetTranscriptionResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetTranscriptionResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type SaveTranscriptionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MeetingId     string                 `protobuf:"bytes,1,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTranscriptionReq) Reset() {
	*x = SaveTranscriptionReq{}
	mi := &file_specs_proto_asr_asr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTranscriptionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTranscriptionReq) ProtoMessage() {}

func (x *SaveTranscriptionReq) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_asr_asr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTranscriptionReq.ProtoReflect.Descriptor instead.
func (*SaveTranscriptionReq) Descriptor() ([]byte, []int) {
	return file_specs_proto_asr_asr_proto_rawDescGZIP(), []int{6}
}

func (x *SaveTranscriptionReq) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

func (x *SaveTranscriptionReq) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SaveTranscriptionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	MeetingId     string                 `protobuf:"bytes,2,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveTranscriptionResp) Reset() {
	*x = SaveTranscriptionResp{}
	mi := &file_specs_proto_asr_asr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveTranscriptionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveTranscriptionResp) ProtoMessage() {}

func (x *SaveTranscriptionResp) ProtoReflect() protoreflect.Message {
	mi := &file_specs_proto_asr_asr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveTranscriptionResp.ProtoReflect.Descriptor instead.
func (*SaveTranscriptionResp) Descriptor() ([]byte, []int) {
	return file_specs_proto_asr_asr_proto_rawDescGZIP(), []int{7}
}

func (x *SaveTranscriptionResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveTranscriptionResp) GetMeetingId() string {
	if x != nil {
		return x.MeetingId
	}
	return ""
}

var File_specs_proto_asr_asr_proto protoreflect.FileDescriptor

const file_specs_proto_asr_asr_proto_rawDesc = "" +
	"\n" +
	"\x19specs/proto/asr/asr.proto\x12\x03asr\"\x10\n" +
	"\x0eHealthCheckReq\")\n" +
	"\x0fHealthCheckResp\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"\x8b\x01\n" +
	"\x12TranscribeAudioReq\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x02 \x01(\tR\tmeetingId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1f\n" +
	"\vsample_rate\x18\x04 \x01(\x05R\n" +
	"sampleRate\"h\n" +
	"\x13TranscribeAudioResp\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x02 \x01(\tR\tmeetingId\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\"4\n" +
	"\x13GetTranscriptionReq\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\"\x90\x01\n" +
	"\x14GetTranscriptionResp\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x1b\n" +
	"\tfull_text\x18\x02 \x01(\tR\bfullText\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x03R\tupdatedAt\"I\n" +
	"\x14SaveTranscriptionReq\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x01 \x01(\tR\tmeetingId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"P\n" +
	"\x15SaveTranscriptionResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x02 \x01(\tR\tmeetingId2\xa1\x02\n" +
	"\n" +
	"AsrService\x128\n" +
	"\vHealthCheck\x12\x13.asr.HealthCheckReq\x1a\x14.asr.HealthCheckResp\x12D\n" +
	"\x0fTranscribeAudio\x12\x17.asr.TranscribeAudioReq\x1a\x18.asr.TranscribeAudioResp\x12G\n" +
	"\x10GetTranscription\x12\x18.asr.GetTranscriptionReq\x1a\x19.asr.GetTranscriptionResp\x12J\n" +
	"\x11SaveTranscription\x12\x19.asr.SaveTranscriptionReq\x1a\x1a.asr.SaveTranscriptionRespB\x11Z\x0fspecs/proto/asrb\x06proto3"

var (
	file_specs_proto_asr_asr_proto_rawDescOnce sync.Once
	file_specs_proto_asr_asr_proto_rawDescData []byte
)

func file_specs_proto_asr_asr_proto_rawDescGZIP() []byte {
	file_specs_proto_asr_asr_proto_rawDescOnce.Do(func() {
		file_specs_proto_asr_asr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_specs_proto_asr_asr_proto_rawDesc), len(file_specs_proto_asr_asr_proto_rawDesc)))
	})
	return file_specs_proto_asr_asr_proto_rawDescData
}

var file_specs_proto_asr_asr_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_specs_proto_asr_asr_proto_goTypes = []any{
	(*HealthCheckReq)(nil),        // 0: asr.HealthCheckReq
	(*HealthCheckResp)(nil),       // 1: asr.HealthCheckResp
	(*TranscribeAudioReq)(nil),    // 2: asr.TranscribeAudioReq
	(*TranscribeAudioResp)(nil),   // 3: asr.TranscribeAudioResp
	(*GetTranscriptionReq)(nil),   // 4: asr.GetTranscriptionReq
	(*GetTranscriptionResp)(nil),  // 5: asr.GetTranscriptionResp
	(*SaveTranscriptionReq)(nil),  // 6: asr.SaveTranscriptionReq
	(*SaveTranscriptionResp)(nil), // 7: asr.SaveTranscriptionResp
}
var file_specs_proto_asr_asr_proto_depIdxs = []int32{
	0, // 0: asr.AsrService.HealthCheck:input_type -> asr.HealthCheckReq
	2, // 1: asr.AsrService.TranscribeAudio:input_type -> asr.TranscribeAudioReq
	4, // 2: asr.AsrService.GetTranscription:input_type -> asr.GetTranscriptionReq
	6, // 3: asr.AsrService.SaveTranscription:input_type -> asr.SaveTranscriptionReq
	1, // 4: asr.AsrService.HealthCheck:output_type -> asr.HealthCheckResp
	3, // 5: asr.AsrService.TranscribeAudio:output_type -> asr.TranscribeAudioResp
	5, // 6: asr.AsrService.GetTranscription:output_type -> asr.GetTranscriptionResp
	7, // 7: asr.AsrService.SaveTranscription:output_type -> asr.SaveTranscriptionResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_specs_proto_asr_asr_proto_init() }
func file_specs_proto_asr_asr_proto_init() {
	if File_specs_proto_asr_asr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_specs_proto_asr_asr_proto_rawDesc), len(file_specs_proto_asr_asr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_specs_proto_asr_asr_proto_goTypes,
		DependencyIndexes: file_specs_proto_asr_asr_proto_depIdxs,
		MessageInfos:      file_specs_proto_asr_asr_proto_msgTypes,
	}.Build()
	File_specs_proto_asr_asr_proto = out.File
	file_specs_proto_asr_asr_proto_goTypes = nil
	file_specs_proto_asr_asr_proto_depIdxs = nil
}
