// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: specs/proto/asr/asr.proto

package asr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AsrService_HealthCheck_FullMethodName       = "/asr.AsrService/HealthCheck"
	AsrService_TranscribeAudio_FullMethodName   = "/asr.AsrService/TranscribeAudio"
	AsrService_GetTranscription_FullMethodName  = "/asr.AsrService/GetTranscription"
	AsrService_SaveTranscription_FullMethodName = "/asr.AsrService/SaveTranscription"
)

// AsrServiceClient is the client API for AsrService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AsrServiceClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error)
	TranscribeAudio(ctx context.Context, in *TranscribeAudioReq, opts ...grpc.CallOption) (*TranscribeAudioResp, error)
	GetTranscription(ctx context.Context, in *GetTranscriptionReq, opts ...grpc.CallOption) (*GetTranscriptionResp, error)
	SaveTranscription(ctx context.Context, in *SaveTranscriptionReq, opts ...grpc.CallOption) (*SaveTranscriptionResp, error)
}

type asrServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAsrServiceClient(cc grpc.ClientConnInterface) AsrServiceClient {
	return &asrServiceClient{cc}
}

func (c *asrServiceClient) HealthCheck(ctx context.Context, in *HealthCheckReq, opts ...grpc.CallOption) (*HealthCheckResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResp)
	err := c.cc.Invoke(ctx, AsrService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asrServiceClient) TranscribeAudio(ctx context.Context, in *TranscribeAudioReq, opts ...grpc.CallOption) (*TranscribeAudioResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscribeAudioResp)
	err := c.cc.Invoke(ctx, AsrService_TranscribeAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asrServiceClient) GetTranscription(ctx context.Context, in *GetTranscriptionReq, opts ...grpc.CallOption) (*GetTranscriptionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTranscriptionResp)
	err := c.cc.Invoke(ctx, AsrService_GetTranscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asrServiceClient) SaveTranscription(ctx context.Context, in *SaveTranscriptionReq, opts ...grpc.CallOption) (*SaveTranscriptionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveTranscriptionResp)
	err := c.cc.Invoke(ctx, AsrService_SaveTranscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsrServiceServer is the server API for AsrService service.
// All implementations must embed UnimplementedAsrServiceServer
// for forward compatibility.
type AsrServiceServer interface {
	HealthCheck(context.Context, *HealthCheckReq) (*HealthCheckResp, error)
	TranscribeAudio(context.Context, *TranscribeAudioReq) (*TranscribeAudioResp, error)
	GetTranscription(context.Context, *GetTranscriptionReq) (*GetTranscriptionResp, error)
	SaveTranscription(context.Context, *SaveTranscriptionReq) (*SaveTranscriptionResp, error)
	mustEmbedUnimplementedAsrServiceServer()
}

// UnimplementedAsrServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAsrServiceServer struct{}

func (UnimplementedAsrServiceServer) HealthCheck(context.Context, *HealthCheckReq) (*HealthCheckResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAsrServiceServer) TranscribeAudio(context.Context, *TranscribeAudioReq) (*TranscribeAudioResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TranscribeAudio not implemented")
}
func (UnimplementedAsrServiceServer) GetTranscription(context.Context, *GetTranscriptionReq) (*GetTranscriptionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTranscription not implemented")
}
func (UnimplementedAsrServiceServer) SaveTranscription(context.Context, *SaveTranscriptionReq) (*SaveTranscriptionResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTranscription not implemented")
}
func (UnimplementedAsrServiceServer) mustEmbedUnimplementedAsrServiceServer() {}
func (UnimplementedAsrServiceServer) testEmbeddedByValue()                    {}

// UnsafeAsrServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AsrServiceServer will
// result in compilation errors.
type UnsafeAsrServiceServer interface {
	mustEmbedUnimplementedAsrServiceServer()
}

func RegisterAsrServiceServer(s grpc.ServiceRegistrar, srv AsrServiceServer) {
	// If the following call pancis, it indicates UnimplementedAsrServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AsrService_ServiceDesc, srv)
}

func _AsrService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsrService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrServiceServer).HealthCheck(ctx, req.(*HealthCheckReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsrService_TranscribeAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TranscribeAudioReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrServiceServer).TranscribeAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsrService_TranscribeAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrServiceServer).TranscribeAudio(ctx, req.(*TranscribeAudioReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsrService_GetTranscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTranscriptionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrServiceServer).GetTranscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsrService_GetTranscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrServiceServer).GetTranscription(ctx, req.(*GetTranscriptionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsrService_SaveTranscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTranscriptionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsrServiceServer).SaveTranscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AsrService_SaveTranscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsrServiceServer).SaveTranscription(ctx, req.(*SaveTranscriptionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AsrService_ServiceDesc is the grpc.ServiceDesc for AsrService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AsrService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asr.AsrService",
	HandlerType: (*AsrServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _AsrService_HealthCheck_Handler,
		},
		{
			MethodName: "TranscribeAudio",
			Handler:    _AsrService_TranscribeAudio_Handler,
		},
		{
			MethodName: "GetTranscription",
			Handler:    _AsrService_GetTranscription_Handler,
		},
		{
			MethodName: "SaveTranscription",
			Handler:    _AsrService_SaveTranscription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "specs/proto/asr/asr.proto",
}
